<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(DotNetTargetFramework)</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TestableIO.System.IO.Abstractions" Version="22.2.0" />
    <PackageReference Include="TestableIO.System.IO.Abstractions.Wrappers" Version="22.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharpEngine.Core.Components\SharpEngine.Core.Components.csproj" />
    <ProjectReference Include="..\..\SharpEngine-Shared\SharpEngine.Shared\SharpEngine.Shared.csproj" />
  </ItemGroup>
</Project>