<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(DotNetTargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="fluentassertions" Version="7.2.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.6.0" />
    <PackageReference Include="Moq" Version="4.20.72" />

    <PackageReference Include="xunit.v3" Version="3.2.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Audio\" />
    <Folder Include="Entities\" />
    <Folder Include="Enums\" />
    <Folder Include="Handlers\" />
    <Folder Include="Windowing\" />
    <Folder Include="Textures\" />
    <Folder Include="Scenes\" />
    <Folder Include="Renderers\" />
    <Folder Include="Primitives\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\SharpEngine.Core\SharpEngine.Core.csproj" />
  </ItemGroup>

</Project>
