name: Publish NuGet Package

on:
  push:
    branches:
      - main

env:
  BuildNumber: 0.0.0

jobs:
  publish:
    runs-on: windows-latest  # Use Windows to support .NET SDK easily

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # TODO: Create variable out of this

      - name: Set build number
        id: set_build_number        
        run: |
          $Year = [System.DateTime]::Now.Year
          $Month = [System.DateTime]::Now.Month.ToString("00")
          $Day = [System.DateTime]::Now.Day.ToString("00")
          $Hour = [System.DateTime]::Now.Hour.ToString("00")
          $Minute = [System.DateTime]::Now.Minute.ToString("00")
          $Version = "{0}.{1}{2}.{3}{4}" -f $Year, $Month, $Day, $Hour, $Minute
          echo "::set-output name=build_number::$Version"

      # TODO: Quality gates (Unit tests, sonar cloud?)

      - name: Debug
        run: cd 

      - name: Restore dependencies
        run: dotnet restore Core/SharpEngine.Core.NET.csproj

      - name: Build project
        run: dotnet build Core/SharpEngine.Core.NET.csproj --configuration Release --no-restore

      # TODO: Create installer for launcher and editor bundle

      - name: Pack NuGet package
        run: dotnet pack Core/SharpEngine.Core.NET.csproj --configuration Release --no-build --output Core/bin/Release/ --version-suffix ${{ env.BuildNumber }}

      - name: Publish to NuGet
        run: dotnet nuget push "Core/bin/Release/SharpEngine.Core.NET.${{ env.BuildNumber }}.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.PUBLISH_NUGET_PACKAGE }} --skip-duplicate

      # TODO: Publish the NuGet package to GitHub.
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_REPO_PACKAGE }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: true

      - name: Upload NuGet package to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_REPO_PACKAGE }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: Core/bin/Release/SharpEngine.Core.NET.${{ env.BuildNumber }}.nupkg
          asset_name: SharpEngine.Core.NET.${{ env.BuildNumber }}.nupkg
          asset_content_type: application/zip
